# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
hello_world <- function() {
    invisible(.Call('_Rtorchcpp_hello_world', PACKAGE = 'Rtorchcpp'))
}

